name: Unity

#on:
  #push:
    #branches: [ "master" ]
  #pull_request:
    #branches: [ "master" ]

jobs:
  unity:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    - run: sudo apt install libfuse2
    - name: Setup Unity
      uses: kuler90/setup-unity@v1
      with:
        unity-modules: android
    - name: Activate Unity
      uses: kuler90/activate-unity@v1
      with:
        unity-username: ${{ secrets.UNITY_USERNAME }}
        unity-password: ${{ secrets.UNITY_PASSWORD }}
        unity-authenticator-key: ${{ secrets.UNITY_AUTHENTICATOR_KEY }}
    - name: Build Unity
      uses: kuler90/build-unity@v1
      with:
        build-target: Android
        build-path: ./build.apk
        android-keystore-base64: >-
                                  /u3+7QAAAAIAAAABAAAAAQANcGxheXN0b3JlIGtleQAAAYOZJEXlAAAFATCCBP0wDgYKKwYBBAEq
                                  AhEBAQUABIIE6VJOXs1TFDHnBNH69C+SiQfpdqJUfapWRxX+0k+EXYqnqKiOFrp0S0UuKrCKj/Au
                                  C2SRwWfOV+u+4p8xlOqJBb8g/3Y1IDd+pCVuUSvrge6OJS7FJiMSRvONJLT1D1TBbTtPO3kvo1Sa
                                  sGx7lCiSJBxJ8LqpM8ivDWOYpD7UZHpM1HidcHScdb7Gc3aiJeRyjFxV3hEje/Z8ftWabEO9+ZhD
                                  Te0HOb8aqjvpVpTRIFoGuKb7Qfbrb1SlQudPFlb5MT0C6t7n8fz1y/G1xa27pLDxXHEgIC1691d3
                                  j5qt1DwKIXcfH94Zqo8wCOxj128ZOH00iUyFUEPkyL29tb+QAg4NHJa48lhXLTwkkvPCJvRWTTdO
                                  SLig1L6eadAQzBcYK3LDA8tFQZ1PG2m4v37LUe4mvOPVOJFuMqOBTlNlBuizg5IbXvksCP6H9aKk
                                  ayzXdmF/bJMRB6qOt55u5zXzn7V1X7jf1nxM0URJm12FFbhPR1T7aInrTWLWBP5pm/PI153RLBPF
                                  oap+v9fflhPO+Rekz5y9Ym4i+Ge2wHM4jVqFIU6vk6+gw9mlPXWrUhNMrXK1wpo3sRSWQ+lXiEfi
                                  +dVq1HQO7s+1tvJo2Q7gEtyCRh61tRIwpLlw/a6eCl8sg3+05Cyp+NQEu1Z67ds3gl07Th9AgQH+
                                  C6BPzNhsCCBZFIrULXBrt8csmwjoalDAJepbCdow+oH1suxlC/vMf3r4DY+3xYQ1GHSR/T7xUlg8
                                  9h8DMQnUF3E5sNj39eTb/jehjviHhF9jcJT0L0Be86Y16JLLoKigyB8WX5f/R2b8aPIG0+RGHeIM
                                  aW4/wTedNTpYBBP6oCkMLYO3iNe6aqbcfepL97CyYsa9lL7S7hou/ROL2wNUeyKU4GOs46w+xID/
                                  /F8ns+cycHIrD6G/oEIcMhR1deB7eLwy7y0jrzdNkksysHTJbvSIHynkJk+KRLExdXwJodVZEf8A
                                  E2CIJdPWELQne2F27NKRveDXm7CHzxVJ37v5Kgk76tJIbYBpA/e/7RfdUB69jauWnhlZ0rkH8mhB
                                  DzlCmuS7GpvZImuTaJc7Trf0A+YnL6BkK8ZQZoQAVU2fvQRiXNOdWEVmeIoxcF6xn5PUwzis+0ZP
                                  U5Nz1wuqVIlqevXWBUQaPxvfM2MDTBYgVXzKsjdse4mS9Oe7UJCooREEbAH45aOMLbKb3hGq3tj0
                                  ZCpBTB3ZzTOpqeCRgJ/XxTRxi1zVfrciUGyPCn/hqUZo02a8qKwKubWKHUKxM5lNpCBVZpcsWt3l
                                  YRNS5RHkoQT1NNngxI5If8AZwxDnhhEqC2LO2x03zHpo9KZo+jWIHgxg/iq4PQDOG+o7yRIwo5b0
                                  xgdEJT0aMwfU5gLsdA7vOjeBBR6p5d2DwD6ArSDC7MtGXGt1o7fZUOuYTV1JQrk0HoWNy2EZvtuj
                                  gmYyERqkPE+jiAzgy+hVsSTPSeYuwNYoJrz0HjJXBhSvt//fzlmVtQLZncya4J5XjiEcrowHdsgF
                                  vrWEMMcc/edEPw/brVYTq57Vg2O7mlFu2tsNsczDjmrVakbS1nCnSMmnNdjuOTN+R6H315uIvpra
                                  2ek7GzzuHUrOv2sFfBMY+oAmu9lQ9qCQpXJf6awT8b08/Jp4RIAKUAm2yKxJ7Zng3HU1ql1gmBcT
                                  MYURBgurKtAw/pLYagAAAAEABVguNTA5AAACpjCCAqIwggGKoAMCAQICBBR/TLMwDQYJKoZIhvcN
                                  AQEFBQAwEjEQMA4GA1UECgwHS3Jha3VsYTAgFw0yMjEwMDIxNDQwMzRaGA8yMDcyMDkxOTE0NDAz
                                  NFowEjEQMA4GA1UECgwHS3Jha3VsYTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAM/A
                                  tdnIQ2KXLul/BP1ooI3RS7l0qJS+0YomliqM0JjwWWtNW7obMo1NB8ePbWHLCfxGdkZacqvR1jA4
                                  d+wuzA6F1dFJMbY92KWne+jl48K9FUO3PW7o0nV6kxNl6VZz0k5fIYSypoYJDX4VN6KKCTF2oeUv
                                  LwJQBoud+2PqvMHmanYEM6l8P7nVSGiMou4XD6mG9L9wvn44IqyMRJvSJmMo1pf8ZzT4kgamKg6j
                                  r1QFxoO8zzjyOPV7eXCUaeUYHkmycXixIi8FcSMQM8ZYskSpT9Sd55CAl+x5ZQkAmrI8cFsXXvkb
                                  G+nDDE5HF/IMEzo1NjBWLavENDw859zZCVMCAwEAATANBgkqhkiG9w0BAQUFAAOCAQEANwO0Kd0Z
                                  V2xQGrJMKnFVFrXlAxxlqGWwrHA8KnL/Id8otcv3am2HGqp+tyoDUEB7xzavi/a1d1vTChApCz3R
                                  uZgj9wVZUMS1BfA/LNpqfGrluZOq9eDNfZUKkfTcf5wEwnAalCeac6G/wzz70W+/jfofxw0M1KwK
                                  caEN4CnyIPoEKr7tjEYZff0k+UynznoEpu++KNbog5hW3PFZkzrbgwd+WNR+qN/6fL0zwVKh0eBQ
                                  OlgjOXqoQe5riajKhj4O4vgC+GU52S4hlTAZPGkyiwPfM2OhfYUXB2AXtEFT+rvPGIZ1qoQEa8er
                                  K7ff4l8UcAHyFG5oyVSOaAkk4Nxe/wc6c+OsR4/onYRSXw6IDlU4J8yu
        android-keystore-pass: ${{ secrets.KEYSTORE_PASS }}
        android-keyalias-name: "playstore key"
        android-keyalias-pass: ${{ secrets.KEYALIAS_PASS }}
